wordpress:
  image: wordpress
  links:
    - database:mysql
  ports:
    - 8080:80
  working_dir: /var/www/html
  volumes:
   - .:/var/www/html/wp-content/themes/development/

database:
  image: mariadb
  environment:
    MYSQL_ROOT_PASSWORD: example
